def draw_star(size, x, y):
  t.up()
  t.goto(x, y)
  t.down()
  t.forward(size)
  t.backward(size/2)
  t.left(60)
  t.up()
  t.forward(size/2)
  t.down()
  t.right(180)
  t.forward(size)
  t.left(180)
  t.forward(size/2)
  t.left(60)
  t.up()
  t.backward(size/2)
  t.down()
  t.forward(size)
